"""Added Facebook username

Revision ID: 5919049b5cf6
Revises: 4efd6d248c8a
Create Date: 2013-11-17 23:55:59.756207

"""

# revision identifiers, used by Alembic.
revision = '5919049b5cf6'
down_revision = '4efd6d248c8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook', sa.Column('username', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facebook', 'username')
    ### end Alembic commands ###
