"""empty message

Revision ID: c000a05a34f
Revises: 561f95cf0044
Create Date: 2013-11-02 12:26:12.906870

"""

# revision identifiers, used by Alembic.
revision = 'c000a05a34f'
down_revision = '561f95cf0044'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook', sa.Column('timezone', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facebook', 'timezone')
    ### end Alembic commands ###
