---
- hosts: all
  vars_files:
    - vars.yml
  gather_facts: false
  user: "{{project_name}}"

  tasks:
  - name: Pull sources from the repository.
    git: repo={{project_repo}} dest=/var/www/{{project_name}}
    notify: 
    - reload uwsgi
    - run migrations

  - name: Delete default nginx config
    sudo: yes
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: Link new nginx config
    sudo: yes
    file: src=/var/www/{{project_name}}/nginx dest=/etc/nginx/sites-enabled/{{project_name}} state=link
    notify: reload nginx

  - name: Install python packages
    pip: requirements=/var/www/{{project_name}}/requirements.txt virtualenv=/home/{{project_name}}/venv/

  - name: Add app directory to python path for virtualenv
    template: dest=/home/{{project_name}}/venv/lib/python2.7/site-packages/app_path.pth src=config/app_path.pth

  - name: Ensure services are started
    sudo: yes
    service: name={{item}} state=started
    with_items: services

  handlers:
    - include: handlers.yml