---
- name: reload nginx
  service: name=nginx state=reloaded
  sudo: yes

- name: reload uwsgi
  service: name=uwsgi state=reloaded
  sudo: yes

- name: run migrations
  shell: source /home/{{project_name}}/venv/bin/activate && alembic upgrade head chdir=/var/www/{{project_name}}/ executable=/bin/bash



