---
- name: reload nginx
  service: name=nginx state=reloaded
  sudo: yes

- name: reload uwsgi
  service: name=uwsgi state=reloaded
  sudo: yes

- name: run migrations
  command: chdir:/var/www/{{project_name}} source /home/fafafa/venv/bin/activate && alembic upgrade head



