---
- name: reload nginx
  service: name=nginx state=reloaded
  sudo: yes

- name: reload uwsgi
  service: name=uwsgi state=reloaded
  sudo: yes

- name: run migrations
  command: source /home/fafafa/venv/bin/activate && cd /var/www/{{project_name}} && export PYTHONPATH=$PYTHONPATH:/var/www/{{project_name}} && alembic upgrade head
