---
- hosts: all
  vars_files:
  - vars.yml
  gather_facts: false
  user: "{{project_name}}"
  sudo: true

  tasks:
  - name: Install system packages
    apt: pkg={{item}} state=latest update-cache=yes
    with_items: system_packages

  - name: Install pip
    easy_install: name=pip

  - name: Install virtualenv
    pip: name=virtualenv

  - name: Install uwsgi
    pip: name=uwsgi

  - name: Set up uwsgi upstart
    template: src=init/uwsgi.conf dest=/etc/init

  - name: Set up nginx upstart
    copy: src=init/nginx.conf dest=/etc/init
